// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/6/2026, 2:51:36 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Project/Van Elvina/van-elvina/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Project/Van Elvina/van-elvina/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Project/Van Elvina/van-elvina/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Project/Van Elvina/van-elvina/plugins/**/*.{js,ts,mjs}","C:/Project/Van Elvina/van-elvina/composables/**/*.{js,ts,mjs}","C:/Project/Van Elvina/van-elvina/utils/**/*.{js,ts,mjs}","C:/Project/Van Elvina/van-elvina/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Project/Van Elvina/van-elvina/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Project/Van Elvina/van-elvina/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Project/Van Elvina/van-elvina/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;