// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 20/6/2026, 4:44:25 am
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Projects/Website/ve-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/Website/ve-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/Website/ve-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/Website/ve-app/plugins/**/*.{js,ts,mjs}","C:/Projects/Website/ve-app/composables/**/*.{js,ts,mjs}","C:/Projects/Website/ve-app/utils/**/*.{js,ts,mjs}","C:/Projects/Website/ve-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/Website/ve-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/Website/ve-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/Website/ve-app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;