<template>
  <div class="min-h-screen bg-warm-ivory text-charcoal font-sans selection:bg-rose-blush selection:text-deep-plum py-16 px-4 sm:px-6 lg:px-8">
    <div class="max-w-4xl mx-auto space-y-12">
      
      <!-- Page Header -->
      <div class="text-center space-y-3">
        <span class="text-xs uppercase tracking-[0.25em] text-deep-plum font-bold font-ui">Terms &amp; Policies</span>
        <h1 class="text-3xl md:text-5xl font-serif font-bold text-deep-plum tracking-wide">Privacy Policy</h1>
        <div class="w-12 h-0.5 bg-deep-plum mx-auto"></div>
      </div>

      <!-- Main Policy Card -->
      <div class="bg-white rounded-3xl border border-rose-blush/30 shadow-premium p-6 md:p-10 space-y-8 relative overflow-hidden">
        <div class="absolute inset-0.5 rounded-[22px] border border-dashed border-rose-blush/20 pointer-events-none"></div>

        <div class="relative z-10 text-xs md:text-sm text-charcoal/80 leading-relaxed space-y-6">
          
          <!-- 1. GENERAL -->
          <div class="space-y-3">
            <h3 class="text-sm md:text-base font-serif font-bold text-deep-plum uppercase tracking-wider">1. General</h3>
            <p>
              1.1 <strong>Van Elvina</strong>, operating from 1/1, Motiwala Complex, Nirala Bazar, Aurangabad, 431001, Maharashtra, India ("we", "us", or "our"), manages and operates the website <a href="/" class="text-deep-plum font-bold hover:underline">www.vanelvina.com</a> (the "Van Elvina Platform"). Through this Platform, we facilitate the sell and purchase of premium intimate wear, sleepwear, shapewear, activewear, and other fashion products ("Products") to our users ("User", "you", or "your").
            </p>
            <p>
              1.2 This Privacy Policy governs your use of the Van Elvina Platform and outlines our guidelines and procedures regarding the collection, storage, possession, handling, processing, transfer, and sharing of personal data provided to us by you. By accessing, browsing, or transacting on the Van Elvina Platform, you consent to our collection and processing of your details in accordance with this Policy.
            </p>
            <p>
              1.3 This document is an electronic record generated by a computer system and does not require any physical or digital signatures. It complies with the relevant provisions of the Information Technology Act, 2000 and the rules made thereunder as applicable in India.
            </p>
            <p>
              1.4 This Policy details what information is collected, the purpose and mode of usage, and to whom such data may be shared or transferred. You may withdraw your consent for data collection at any time by contacting our support team; however, doing so may limit our ability to provide corresponding services or fulfill orders.
            </p>
          </div>

          <!-- Divider -->
          <div class="border-t border-rose-blush/10"></div>

          <!-- 2. TYPE OF INFORMATION COLLECTED -->
          <div class="space-y-3">
            <h3 class="text-sm md:text-base font-serif font-bold text-deep-plum uppercase tracking-wider">2. Type of Information Collected</h3>
            <p>
              2.1 We collect data when you navigate, register, search, or buy on the Platform. You agree to provide true, correct, up-to-date, and accurate information. You can review, update, or request deletion of your information by getting in touch with us.
            </p>
            <p>
              2.2 The Platform is not intended for use by minors. We do not knowingly collect personal details from users under 18 years of age. If we learn that we have inadvertently collected information from a person under 18, we will take steps to delete that data from our servers.
            </p>
            <p>
              2.3 We may collect details that identify you ("Personal Information"), such as your full name, email address, residential address, telephone number, gender, and birth date.
            </p>
            <p>
              2.4 We may also process or store certain sensitive details ("Sensitive Personal Data or Information") necessary to secure account access and process payments, consisting of account passwords and encrypted billing info (processed through secure third-party payment gateways).
            </p>
          </div>

          <!-- Divider -->
          <div class="border-t border-rose-blush/10"></div>

          <!-- 3. USE OF INFORMATION COLLECTED -->
          <div class="space-y-3">
            <h3 class="text-sm md:text-base font-serif font-bold text-deep-plum uppercase tracking-wider">3. Use of Information Collected</h3>
            <p>
              We process your details for the following purposes:
            </p>
            <ul class="list-disc list-inside pl-4 space-y-1.5">
              <li>To register, maintain, and secure your account profile on our Platform.</li>
              <li>To package, deliver, and process your orders, and handle cash-on-delivery or digital payments.</li>
              <li>To send you transactional updates, order confirmations, invoice details, and support notices.</li>
              <li>To conduct internal research and analysis in order to optimize our catalog, sizing guides, and web experience.</li>
              <li>To comply with legal regulations, tax obligations, or requests from judicial authorities.</li>
              <li>To resolve customer disputes, returns, or technical grievances.</li>
              <li>To detect and prevent fraudulent transactions or security violations.</li>
            </ul>
          </div>

          <!-- Divider -->
          <div class="border-t border-rose-blush/10"></div>

          <!-- 4. DISCLOSURE OF INFORMATION -->
          <div class="space-y-3">
            <h3 class="text-sm md:text-base font-serif font-bold text-deep-plum uppercase tracking-wider">4. Disclosure of Information</h3>
            <p>
              4.1 We share necessary details with trusted third-party service providers (such as shipping companies, courier partners, and digital payment gateway companies) to deliver your orders. These service providers are bound by strict confidentiality terms and security guidelines.
            </p>
            <p>
              4.2 We may disclose information when required by legal mandates, court decrees, or government orders, or when we believe in good faith it is necessary to protect rights, prevent fraud, or ensure property security.
            </p>
            <p>
              4.3 In the event of a business merger, asset sale, or transfer of ownership, customer database records may be transferred to the successor entity, subject to data protection policies at least as protective as those in this Privacy Policy.
            </p>
            <p>
              4.4 Payment information is handled directly through encrypted, secure, PCI-DSS compliant third-party payment gateways. Van Elvina does not view or store your credit/debit card numbers or net banking passwords. We are not liable for any issues, transaction failures, or breaches arising at the payment carrier level.
            </p>
          </div>

          <!-- Divider -->
          <div class="border-t border-rose-blush/10"></div>

          <!-- 5. SECURITY -->
          <div class="space-y-3">
            <h3 class="text-sm md:text-base font-serif font-bold text-deep-plum uppercase tracking-wider">5. Data Security</h3>
            <p>
              5.1 We implement appropriate physical, electronic, and administrative security measures (such as SSL encryption, access controls, and firewalls) to prevent unauthorized access, loss, or leakage of your data.
            </p>
            <p>
              5.2 While we follow industry-recognized standards to protect your details, you acknowledge that no transmission method over the internet is 100% secure. We cannot guarantee absolute security and disclaim liability for security breaches or actions of third parties beyond our reasonable control (e.g. hacking, server crashes, system failures).
            </p>
          </div>

          <!-- Divider -->
          <div class="border-t border-rose-blush/10"></div>

          <!-- 6. COOKIES POLICY -->
          <div class="space-y-3">
            <h3 class="text-sm md:text-base font-serif font-bold text-deep-plum uppercase tracking-wider">6. Cookies Policy</h3>
            <p>
              6.1 We use cookies and similar tracking tools to log browser type, IP addresses, internet service providers, and referral URLs. This help us analyze trends and tailor products.
            </p>
            <p>
              6.2 Temporary cookies store login sessions and preferences. We do not store unencrypted personal information in cookies. You can disable or wipe cookies through your browser configurations, though this might limit functionality on certain parts of the Platform.
            </p>
          </div>

          <!-- Divider -->
          <div class="border-t border-rose-blush/10"></div>

          <!-- 7. GRIEVANCE REDRESSAL -->
          <div class="space-y-3 bg-rose-blush/10 p-6 rounded-2xl border border-rose-blush/20">
            <h3 class="text-sm md:text-base font-serif font-bold text-deep-plum uppercase tracking-wider">7. Grievance Redressal</h3>
            <p>
              If you have any questions, feedback, or complaints regarding this Privacy Policy or data handling practices, please contact our support desk:
            </p>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2 text-xs">
              <div>
                <span class="block font-bold text-deep-plum uppercase tracking-wider">Grievance Desk</span>
                <p class="font-semibold text-charcoal/80 mt-0.5">Kiruba Devi (Support Desk)</p>
              </div>
              <div>
                <span class="block font-bold text-deep-plum uppercase tracking-wider">Email Address</span>
                <p class="font-semibold text-charcoal/80 mt-0.5"><a href="mailto:support@vanelvina.com" class="hover:underline">support@vanelvina.com</a></p>
              </div>
              <div>
                <span class="block font-bold text-deep-plum uppercase tracking-wider">Address Details</span>
                <p class="font-semibold text-charcoal/80 mt-0.5">1/1, Motiwala Complex, Nirala Bazar, Aurangabad, 431001, Maharashtra.</p>
              </div>
            </div>
          </div>

          <!-- Divider -->
          <div class="border-t border-rose-blush/10"></div>

          <!-- 8. GOVERNING LAW & SEVERABILITY -->
          <div class="space-y-3">
            <h3 class="text-sm md:text-base font-serif font-bold text-deep-plum uppercase tracking-wider">8. Governing Law &amp; Severability</h3>
            <p>
              8.1 This Privacy Policy shall be governed by and construed in accordance with the laws of India. Any disputes arising out of this Policy shall be subject to the exclusive jurisdiction of the competent courts in Aurangabad, Maharashtra.
            </p>
            <p>
              8.2 If any clause or portion of this Privacy Policy is deemed invalid or unenforceable by a court of competent jurisdiction, the remaining provisions of the Policy shall continue in full force and effect.
            </p>
          </div>

        </div>
      </div>

    </div>
  </div>
</template>

<script setup lang="ts">
// SEO Settings
useHead({
  title: 'Privacy Policy — Van Elvina',
  meta: [
    { name: 'description', content: 'Read the Privacy Policy of Van Elvina. Understand how we collect, store, and protect your personal information and transaction details.' }
  ]
})
</script>

<style scoped>
.shadow-premium {
  box-shadow: 0 20px 40px -15px rgba(138, 79, 90, 0.12);
}
</style>
